/**
 * Phase 25J — Outbound Email Idempotency Hardening. Establishes the ONE
 * stable identity every Email-channel send is keyed on, derived purely
 * from the `communications` row's own primary key
 * (`communications.id bigint generated always as identity` — a single
 * global sequence across every company, confirmed immutable and never
 * regenerated by any retry/reclaim path in `communication-service.ts`).
 * No new column, no new table: the identity is a pure function of an
 * id that already exists, persisted, and never changes for the
 * lifetime of a communication — so it never needs storing itself.
 *
 * This is deliberately NOT a claim that VYRON can make an arbitrary
 * SMTP/API provider idempotent on its own — SMTP has no universal
 * idempotency mechanism. What this establishes is the stable identity a
 * real provider integration can hand to a provider that DOES support
 * idempotency (e.g. an `Idempotency-Key` header), and/or use as the
 * email's own `Message-ID` header, so that when that integration is
 * eventually built, retrying a communication is provably the same
 * logical send attempt as the first one — not a new one.
 *
 * RETRY vs RESEND (the distinction this whole design exists to protect):
 * - A RETRY reuses the SAME `communications` row (`Queued`/`Sending`/
 *   `Failed` cycling on one id, driven by `processCommunicationQueue`'s
 *   claim/reclaim logic) — same id, same identity, every time.
 * - A RESEND is a NEW, deliberate call to `queueCommunication` (e.g. a
 *   user clicking "Send Email" again from `document-email-service.ts`),
 *   which creates a genuinely NEW `communications` row with a NEW id —
 *   and therefore a NEW identity. This file has no way to conflate the
 *   two, by construction: it only ever receives a `communications.id`,
 *   never anything a caller could reuse across two different rows.
 */

const DEFAULT_MESSAGE_ID_DOMAIN = "communications.vyronfinance.co.za";

/** The domain part of the Message-ID this deployment generates — a
 * VYRON-controlled identifier, not a customer/provider domain. Falls
 * back to a safe, non-throwing default (unlike the inbound bank-
 * statement-email domain, this is not a live routable address anything
 * depends on resolving — RFC 5322 only requires the Message-ID's domain
 * part to be a domain the generator controls, not that it resolve) so
 * this never blocks a send in an environment that hasn't set it. */
function messageIdDomain(): string {
  return process.env.VYRON_MESSAGE_ID_DOMAIN?.trim() || DEFAULT_MESSAGE_ID_DOMAIN;
}

export type CommunicationIdempotencyIdentity = {
  /** A plain, provider-agnostic token safe to pass as an idempotency
   * key/header to any provider that supports one (e.g. an
   * `Idempotency-Key` header) — no `@`, no angle brackets, just
   * `[a-z0-9-]`. */
  idempotencyKey: string;
  /** An RFC 5322-shaped `<local-part@domain>` Message-ID, safe to use
   * as the email's own `Message-ID` header. */
  messageId: string;
};

/** The ONE place this identity is computed — deterministic, pure, no
 * I/O. Contains no customer PII (no email address, no customer name),
 * no business-document number (no invoice number), and no timestamp —
 * only the communication's own opaque internal id, which is stable
 * across every retry and reclaim by construction (those paths all
 * operate on the same row, never creating a new one). */
export function buildCommunicationIdempotencyIdentity(communicationId: number): CommunicationIdempotencyIdentity {
  return {
    idempotencyKey: `vyron-communication-${communicationId}`,
    messageId: `<vyron-communication-${communicationId}@${messageIdDomain()}>`,
  };
}
