-- Financial Reporting & Executive Intelligence Platform (Module 9).
--
-- Research confirmed (before writing anything here) that the real GL
-- read primitives already exist and are scale-safe: `fn_trial_balance`
-- (DB-side aggregate, `trial-balance-service.ts`), `gl-inquiry-service.ts`
-- (keyset-paginated), `account-activity-service.ts` (per-account period
-- movement). Every statement/report this module adds is a GROUPING layer
-- on top of those — never a second GL query path. `chart_of_accounts`
-- already carries real `branch_id`/`department_id`/`cost_centre_id`
-- dimensions (consumed by GL Inquiry today) and real, previously-unused
-- `reporting_group`/`financial_statement_group` columns this module
-- finally reads. "Project" is the one genuinely new dimension, added
-- here as a real business object mirroring Branches/Departments/Cost
-- Centres exactly — "One Business Object," not a fourth-different shape.

create table projects (
  id bigint generated always as identity primary key,
  company_id uuid not null references companies (id) on delete cascade,
  name text not null,
  code text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (company_id, code)
);

alter table projects enable row level security;
create policy "members can access their company's projects" on projects for all using (user_can_access_company(company_id));

alter table chart_of_accounts
  add column project_id bigint references projects (id) on delete set null;

-- Budgets — genuinely new, no prior entity. Amount per account per
-- financial year, optionally scoped to a dimension (branch/department/
-- cost centre/project) for "Budget vs Actual" management reporting;
-- null dimension columns mean "whole company."
create table budgets (
  id bigint generated always as identity primary key,
  company_id uuid not null references companies (id) on delete cascade,
  account_id bigint not null references chart_of_accounts (id) on delete cascade,
  financial_year_label text not null,
  branch_id bigint references branches (id) on delete set null,
  department_id bigint references departments (id) on delete set null,
  cost_centre_id bigint references cost_centres (id) on delete set null,
  project_id bigint references projects (id) on delete set null,
  amount numeric(14, 2) not null default 0,
  created_by text not null default 'System',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (company_id, account_id, financial_year_label, branch_id, department_id, cost_centre_id, project_id)
);

create index budgets_company_id_idx on budgets (company_id, financial_year_label);

alter table budgets enable row level security;
create policy "members can access their company's budgets" on budgets for all using (user_can_access_company(company_id));

-- Report Designer — saved report layouts. `columns`/`groups`/`filters`/
-- `calculated_fields` are real jsonb structures the Report Designer UI
-- reads/writes; nothing about a report's LAYOUT is hardcoded in
-- application code (the base data it draws from — Trial Balance/Income
-- Statement/etc — is still generated by the one real engine per type).
create table report_definitions (
  id bigint generated always as identity primary key,
  company_id uuid not null references companies (id) on delete cascade,
  name text not null,
  report_type text not null check (report_type in (
    'TrialBalance', 'IncomeStatement', 'BalanceSheet', 'CashFlow', 'GLInquiry', 'BudgetVsActual', 'Custom'
  )),
  columns jsonb not null default '[]',
  groups jsonb not null default '[]',
  filters jsonb not null default '{}',
  calculated_fields jsonb not null default '[]',
  created_by text not null default 'System',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index report_definitions_company_id_idx on report_definitions (company_id);

alter table report_definitions enable row level security;
create policy "members can access their company's report definitions" on report_definitions for all using (user_can_access_company(company_id));

-- Executive Alerts — same rich shape as Banking/VAT Exceptions (reason/
-- evidence/recommended-action/status/resolution-history), not the
-- lighter `notifications` shape (title/message/severity only) — an
-- Executive Alert genuinely needs the Exception Centre's richness, so it
-- follows that established pattern rather than being forced into the
-- Notification one. A companion row is still written to the EXISTING
-- `notifications` table for each alert raised (reusing an existing
-- `notification_type` value — no CHECK-constraint change needed) so the
-- bell icon surfaces it too; `executive_alerts` stays the source of
-- truth for the Executive Alerts workspace itself.
create table executive_alerts (
  id bigint generated always as identity primary key,
  company_id uuid not null references companies (id) on delete cascade,
  alert_type text not null check (alert_type in (
    'DecliningCash', 'IncreasingDebtors', 'SlowPayingCustomers', 'SupplierRisk',
    'MarginReduction', 'InventoryProblems', 'ComplianceIssues', 'AutomationFailures',
    'LargeUnusualTransactions', 'DuplicateTrends'
  )),
  priority text not null default 'Medium' check (priority in ('Low', 'Medium', 'High', 'Critical')),
  reason text not null default '',
  evidence text not null default '',
  recommended_action text not null default '',
  related_type text,
  related_id bigint,
  status text not null default 'Open' check (status in ('Open', 'Resolved', 'Dismissed')),
  resolved_by text,
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz not null default now(),
  unique (company_id, alert_type, related_type, related_id, status)
);

create index executive_alerts_company_status_idx on executive_alerts (company_id, status);

alter table executive_alerts enable row level security;
create policy "members can access their company's executive alerts" on executive_alerts for all using (user_can_access_company(company_id));
